language: erlang
sudo: false

os: linux
otp_release:
   - 19.3
   - 18.3
   - 17.5
   - R16B03-1

addons:
  apt:
    packages:
    - build-essential
    - curl
    - libcurl4-openssl-dev
    - libicu-dev
    - libmozjs185-dev
    - pkg-config
    - python-requests
    - python-sphinx
    - python-virtualenv
#    - sphinx-rtd-theme
    - help2man
    - shunit2

python:
  - "2.7"

git:
  depth: 10

# logfile uploader uses requests
cache:
  - pip

# logfile uploader credentials
env:
  global:
    - secure: "UdA/gKIlyuXaW+hUgRx40t1TYjLCGxMqHvM5Uw7UbUH2dqEkgJiLfhZGchS1JVzl8M01VKZUUzS7v2nvRLiHZN1kvaw5kfq31VRoafUah8jfmvqNWZVdLovHl3aw5UX/HRt0RkbWbhdbdknTfh6+YinSZ+Nb54jCErMg9nabXtM="
    - COUCHDB_IO_LOG_DIR=/tmp/couchjslogs

# Enable this block if you want to build docs & fauxton too
#node_js:
#  - 6
#before_script:
#  - ./configure -c

# Then comment this section out
before_script:
  - rm -rf /tmp/couchjslogs
  - mkdir -p /tmp/couchjslogs
  - ./configure -c --disable-docs --disable-fauxton
  - cd src/mango
  - make venv
  - source venv/bin/activate
  - make pip-install
  - cd ..

script:
   - make mango-test

after_failure:
  - build-aux/logfile-uploader.py

# Re-enable once test suite is reliable
#notifications:
#  email: false
#  irc:
#    channels:
#      "irc.freenode.org#couchdb-dev"
#  on_success: change
#  on_failure: always
#  use_notice: true
#  skip_join: true
#  template:
#    - %{repository_slug}/%{branch}: %{message} %{build_url}"
