before_install:
   - sudo apt-get -y update
   - sudo apt-get -y install libicu-dev libmozjs-dev pkg-config help2man
   - sudo apt-get -y install libtool automake autoconf autoconf-archive
   - sudo apt-get -y install texlive-latex-base texlive-latex-recommended
   - sudo apt-get -y install texlive-latex-extra texlive-fonts-recommended texinfo
   - sudo apt-get -y install python-pygments python-docutils python-sphinx
before_script: ./bootstrap && ./configure
script:
   - rm erlang-*.tar.bz2
   - make distcheck
   - cd src/fauxton
   - npm install
   - grunt test
language: erlang
otp_release:
   - 19.0
   - 18.3
   - 17.0
   - R16B03-1
   - R15B03
   - R14B04
